// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;

namespace TestProject1
{
  [TestFixture]
  public class ValidacijafilteraizkategorijeAutomobiliTest
  {
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
      driver = new FirefoxDriver();
      js = (IJavaScriptExecutor)driver;
      vars = new Dictionary<string, object>();
    }
    [TearDown]
    protected void TearDown()
    {
      driver.Quit();
      driver.Dispose();
    }
    [Test]
    public void validacijafilteraizkategorijeAutomobili()
    {
      driver.Navigate().GoToUrl("https://olx.ba/");
      driver.Manage().Window.Maximize();
      Thread.Sleep(5000);
      driver.FindElement(By.CssSelector(".css-1sjubqu")).Click();
      driver.FindElement(By.CssSelector(".main-category-icon > img")).Click();
      Thread.Sleep(1000);
      driver.FindElement(By.LinkText("Automobili")).Click();
      Thread.Sleep(1000);
      driver.FindElement(By.CssSelector(".relative:nth-child(6) > div > .flex")).Click();
      driver.FindElement(By.CssSelector(".relative:nth-child(7) > div > .flex")).Click();
      driver.FindElement(By.CssSelector(".relative:nth-child(8) > div > .flex")).Click();
      driver.FindElement(By.CssSelector(".main-btn")).Click();
      driver.FindElement(By.CssSelector(".modal-header > .h-6")).Click();
      driver.Close();
    }
  }
}